//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAccountService")]
public interface IAccountService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Request", ReplyAction="http://tempuri.org/IAccountService/RequestResponse")]
    string Request(string xmlstring);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Echo", ReplyAction="http://tempuri.org/IAccountService/EchoResponse")]
    string Echo();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IAccountServiceChannel : IAccountService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class AccountServiceClient : System.ServiceModel.ClientBase<IAccountService>, IAccountService
{
    
    public AccountServiceClient()
    {
    }
    
    public AccountServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Request(string xmlstring)
    {
        return base.Channel.Request(xmlstring);
    }
    
    public string Echo()
    {
        return base.Channel.Echo();
    }
}
